# Generated by Django 3.2.7 on 2021-11-24 10:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseDocument',
        ),
        migrations.CreateModel(
            name='CourseDocumentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('courseName', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_documents', to='backend.course')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
