# Generated by Django 3.2.7 on 2021-12-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='Answer',
            field=models.TextField(verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='Question',
            field=models.TextField(verbose_name='Questions'),
        ),
    ]
