# Generated by Django 3.2.7 on 2022-01-26 04:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211207_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='Answer',
            field=wagtail.core.fields.RichTextField(verbose_name='Answers'),
        ),
    ]
